sudo: required

language: php
  - 7.0
services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - docker run -d --name camunda -p 8080:8080 bashkirtsevich/camunda

install:
  - docker run -v $PWD:/app borodulin/php:7.0 composer install

script:
  - docker run -v $PWD:/app borodulin/php:7.0 vendor/bin/codecept run
