sudo: required

language: php
  - 7.0
  - 7.1
services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - docker pull camunda/camunda-bpm-platform:latest
  - docker run -d --name camunda -p 8080:8080 camunda/camunda-bpm-platform:latest

install:
  - composer update

script:
  - php vendor/bin/codecept run