sudo: required

language: php
  - 7.0
  - 7.1
services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - docker pull bashkirtsevich/camunda
  - docker run -d --name camunda -p 8080:8080 bashkirtsevich/camunda

install:
  - composer install

script:
  - php vendor/bin/codecept run