sudo: required

language: php
  - 7.0
services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - docker network create camunda
  - docker run -d --net=camunda --name camunda bashkirtsevich/camunda

install:
  - docker run -v $PWD:/app borodulin/php:7.0 composer install

script:
  - docker run --net=camunda -v $PWD:/app borodulin/php:7.0 vendor/bin/codecept run
